export default [
  { header: 'account' },
  { name: 'cfx_getAccount', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getBalance', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getStakingBalance', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getCollateralForStorage', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getNextNonce', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { divider: true },

  { header: 'contract' },
  { name: 'cfx_getAdmin', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getCode', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getStorageRoot', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getSponsorInfo', inputs: [{ name: 'address', type: 'address' }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getStorageAt', inputs: [{ name: 'address', type: 'address' }, { name: 'position', type: 'uint256' }, { name: 'epochNumber', type: 'uint256' }] },
  { divider: true },

  { header: 'block' },
  { name: 'cfx_epochNumber', inputs: [] },
  { name: 'cfx_getBestBlockHash', inputs: [] },
  { name: 'cfx_getBlockByHash', inputs: [{ name: 'blockHash', type: 'bytes32' }, { name: 'transactions', type: 'bool' }] },
  { name: 'cfx_getBlockByEpochNumber', inputs: [{ name: 'epochNumber', type: 'uint256' }, { name: 'transactions', type: 'bool' }] },
  { name: 'cfx_getBlocksByEpoch', inputs: [{ name: 'epochNumber', type: 'uint256' }] },
  { divider: true },
  
  { header: 'transaction' },
  { name: 'cfx_getTransactionByHash', inputs: [{ name: 'hash', type: 'bytes32' }] },
  { name: 'cfx_getTransactionReceipt', inputs: [{ name: 'hash', type: 'bytes32' }] },
  { name: 'cfx_sendRawTransaction', inputs: [{ name: 'data', type: 'bytes' }] },
  { name: 'cfx_call', inputs: [{ name: 'tx', type: 'tuple', components: [
    { name: 'from', type: 'address' },
    { name: 'to', type: 'address' },
    { name: 'gas', type: 'uint256' },
    { name: 'gasPrice', type: 'uint256' },
    { name: 'value', type: 'uint256' },
    { name: 'data', type: 'bytes' },
    { name: 'nonce', type: 'uint256' },
  ] }, { name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_estimateGasAndCollateral', inputs: [{ name: 'tx', type: 'tuple', components: [
    { name: 'from', type: 'address' },
    { name: 'to', type: 'address' },
    { name: 'gas', type: 'uint256' },
    { name: 'gasPrice', type: 'uint256' },
    { name: 'value', type: 'uint256' },
    { name: 'data', type: 'bytes' },
    { name: 'nonce', type: 'uint256' },
  ] }, { name: 'epochNumber', type: 'uint256' }] },
  { divider: true },

  { header: 'others' },
  { name: 'cfx_gasPrice', inputs: [] },
  { name: 'cfx_getInterestRate', inputs: [{ name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getAccumulateInterestRate', inputs: [{ name: 'epochNumber', type: 'uint256' }] },
  { name: 'cfx_getLogs', inputs: [{ name: 'filter', type: 'tuple', components: [
    { name: 'fromEpoch', type: 'uint256' },
    { name: 'toEpoch', type: 'uint256' },
    { name: 'blockHashes', type: 'bytes32[]' },
    { name: 'address', type: 'address[]' },
    { name: 'topics', type: 'bytes[]' },
    { name: 'limit', type: 'uint32' },
  ] }] },
]